name: complex-networks
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _x86_64-microarch-level=3
  - aom=3.6.0
  - asttokens=3.0.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - cffi=1.17.1
  - comm=0.2.1
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.1
  - fontconfig=2.15.0
  - fonttools=4.59.2
  - freetype=2.13.3
  - fribidi=1.0.10
  - gmp=6.3.0
  - graph-tool-base=2.98
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.2
  - intel-openmp=2025.0.0
  - ipykernel=6.30.1
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.8
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.1.1
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libcups=2.4.2
  - libcurl=8.15.0
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.16
  - libkrb5=1.21.3
  - libllvm15=15.0.7
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mesalib=25.1.5
  - mkl=2025.0.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mysql=8.4.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - numexpr=2.11.0
  - numpy=2.3.3
  - numpy-base=2.3.3
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openssl=3.5.4
  - packaging=25.0
  - pandas=2.3.2
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python=3.13.7
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyzmq=27.1.0
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - readline=8.3
  - scipy=1.16.2
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.17.0
  - sparsehash=2.0.4
  - spirv-tools=2025.1
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - tzdata=2025b
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xextproto=7.3.0
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
prefix: /home/ikerbenidorm/miniconda3/envs/complex-networks
